### ISSUE TITLE
Some sample code would be great

### ISSUE THREAD

**Issue by helloniklas** [dowjones/graphql-dynamodb-connections#1]
I'm new to GraphQL and just evaluating it. This seems like it would be necessary to be able to get it to work with dynamodb. Any chance of adding some simple samples of how to use this.

**Comment by codepreneur** [comment]
@helloniklas I added a complete example on how to get started, let me know if you have any problems getting it to work.

**Comment by nemtsov** [comment]
@helloniklas did @codepreneur 's example help?
